version: '3.7'
services:
  influxdb:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.influxdb
    image: influxdb:1.7-alpine
    ports:
      - "8086:8086"
    command:
      - '-config'
      - '/etc/influxdb/influxdb.conf'
    environment:
      INFLUXDB_REPORTING_DISABLED: "false"
      INFLUXDB_DB: k6
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-data:/var/lib/influxdb
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafanadb
  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: 'version'
volumes:
  influxdb-data:
  grafana-data:
