version: '3.7'
services:
  influxdb:
    image: influxdb:1.7-alpine
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_PASSWORD: pass
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_DB: k6
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_REPORTING_DISABLED: "false"
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: pass
    volumes:
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:6.5.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafanadb
  k6:
    image: loadimpact/k6:0.26.0
    # ports:
    #   - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: 'version'
volumes:
  influxdb-data:
  grafana-data:
